name: books_app_test
description: books app test assignment.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  chopper: ^4.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0
  riverpod: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.5
  chopper_generator: ^4.0.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  json_serializable: ^6.0.1
flutter:
  uses-material-design: true
